# Generated by Django 3.1.2 on 2022-03-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_small', models.ImageField(help_text='Image size 70x62', upload_to='games/small/')),
                ('cover_normal', models.ImageField(help_text='Image size 200x250', upload_to='games/normal/')),
                ('cover_big', models.ImageField(help_text='Image size 1280x720 or above', upload_to='games/big/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.category')),
            ],
        ),
    ]
